### ISSUE TITLE
Vysvětlující věta k OCR

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-OCR#1]
Prosím o přidání vysvětlující věty na stránku s OCR: 

Pouze 3 jednoduché kroky a z fotografie textu máte k dispozici editovatelný text. 

Zároveň přikládám grafické znázornění využívání OCR, který může sloužit jako návod, mám i formát .svg, který můžu poslat mailem, pokud ho budete potřebovat. 
![ocr-diagram](https://user-images.githubusercontent.com/15922183/54687345-a8d14d00-4b1b-11e9-9841-143983edea7d.jpg)

**Comment by rudky4** [comment]
@nnis prosim o zaslanie obrázku v mailom, ideálne ako SVG alebo PNG.

**Comment by nnis** [comment]
Měl byste to mít v mailu.

**Comment by rudky4** [comment]
@nnis text+obrázok doplnený: http://inqooltest.libj.cas.cz/ocr-web/ dodané SVG sa žiaľ nevykresľovalo správne, prípadne by možno pomohol export do PNG vo vyššom rozlíšeni? (alebo to zatiaľ necháme tak).

**Comment by nnis** [comment]
Koukala jsem na to i na telefonu a vypadá to myslím v pohodě, tak to zatím nechme takhle a kdyby něco, vyexportuji obrázek znovu. Díky
