### ISSUE TITLE
Titulní strana OCR

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-OCR#2]
Hledala jsem inspiraci a OCR služba mi přijde podstatou podobná jako služby na mergování pdf filů. Přidávám nápady na inspiraci a návrh na úpravu rozložení prvků na stránce. Zároveň navrhuji sdílet informace o "ostatních produktech z rodiny INDIHU", abychom zvýšili povědomí o projektu a nalákali skrz jednu službu i na ty ostatní. 

Viz: https://www.pdfmerge.com/ 
![ocr-napad2](https://user-images.githubusercontent.com/15922183/57680832-c825bb80-762e-11e9-8d47-71f612ed8af0.png)

Viz: https://combinepdf.com/
Z této stránky bych okopírovala to sdílení, když už ho navíc máme z INDIHU Exhibition 
![ocr-napad](https://user-images.githubusercontent.com/15922183/57681761-a0375780-7630-11e9-8138-b9b417703220.png)

https://www.foxitsoftware.com/merge-pdf/
![ocr-napad4](https://user-images.githubusercontent.com/15922183/57681964-0d4aed00-7631-11e9-8f4b-e69b7aad4888.png)

Zvětšení a zvýraznění prostoru pro vkládání/přetažení dokumentů. Ptám se, nabízíme také import z Drive či z Dropboxu nebo jiných služeb na ukládání? Viz: https://smallpdf.com/merge-pdf
![ocr-napad3](https://user-images.githubusercontent.com/15922183/57682084-4a16e400-7631-11e9-8e41-8057a0f95eb3.png)

Finální stránka by tedy měla: 
- mít font a barevnost jako INDIHU Exhibition
- modrou lištu v záhlaví
- šedou patku
- vše by se mělo vejít na stránku bez scrollování
- podkladový obrázek
- odkaz (menu) s dalšími produkty INDIHU v záhlaví

Podkladové foto
![ocr-podkladove-foto](https://user-images.githubusercontent.com/15922183/57685660-ae897180-7638-11e9-8d32-693615eaa00a.jpg) - k volnému použití zde: https://www.pexels.com/photo/white-printer-paper-2249432/ 

Rozložení prvků na stránce plus vysvětlení: 
![ocr-hp-wireframe](https://user-images.githubusercontent.com/15922183/57686402-d7f6cd00-7639-11e9-947d-7870fa573b36.jpg)

Textace: 
Získejte snadno a zdarma z obrázku textu editovatelný text (Velké písmo)

Podporujeme češtinu, angličtinu, slovenštinu, němčinu, ruštinu, francouzštinu, španělštinu a latinu. Vystupními formáty je .pdf nebo .txt. (menší písmo - písmo viz INDIHU Exhibition)

Přesuňte soubory
Vyberte soubory

Víte o někom, kdo OCR využije? 

Menu na přepínání mezi ostatními produkty INDIHU: 
INDIHU Exhibition (nástroj na tvorbu virtuálních výstav)
O projektu INDIHU (odkaz na web indihu.cz) 

Ještě dodám nový diagram, který nahradí ten původní a bude na výšku, jen mi to chvíli zabere.

**Comment by nnis** [comment]
Přikládám odkazy na nové diagramy
https://drive.google.com/open?id=1nI2gbBhb0T_vbSOHOE1YIKHc5SAMRYrC

https://drive.google.com/open?id=1ce8URCNTI5ve_CXuE9C2gvyUtZQjDIog

https://drive.google.com/open?id=1aczNrbKsQl9IQPP3JluKwLheLpkSMej_

https://drive.google.com/open?id=1efoTwWDiPtv58XBxyNiO5Vq8IpmDhuIA

**Comment by rudky4** [comment]
@nnis po dlhšom čase má OCR web kompletne nový frontend: http://inqooltest.libj.cas.cz/ocr-web/

**Comment by motyc** [comment]
Vypadá to skvěle! Poznámky z první dobré:

- gramatická chyba - "Vystupními formáty je .pdf nebo .txt" -> "Vystupními formáty jsou .pdf nebo .txt"
- návrh lepšího znění (neopakuje se slovo) - "Získejte snadno a zdarma z obrázku textu editovatelný text" -> "Získejte snadno a zdarma z obrázku textu editovatelný dokument"
- návrh lepšího znění (mluví se o nástroji) - "Podporujeme češtinu, angličtinu, slovenštinu, ..." -> "Podporována je čeština, angličtina, slovenština, ..."
- upřesnění u selectu - "Jazyk" -> "Jazyk vstupního textu"
- upřesnění nápovědy (Jak zlepšit kvalitu výstupu) - nad body bych přidal - "Dodržujte tyto zásady pro vstupní obrázky:" + poslední bod ("K úpravě obrázků můžete použít nástroj IrfanView") dát jako nový odstavec bez puntíku.

**Comment by rudky4** [comment]
@motyc upraveno

**Comment by nnis** [comment]
Díky moc za textaci, rozhodně to prokouklo. A celá stránka vypadá rozhodně líp. Ještě bych poprosila o úpravu v tom smyslu, že modrý obdelník pro přesun textu bude na stejnou šířku jako ty řádky pod ním a bude mít zaoblené rohy jako ostatní ovládaví prvky. Grafické znázornění procesu by bylo více vpravo a větší. Klidně na celou výšku. 

Spodní lištu prosím rozdělte v půlce. 

Upozornění o zkopírovaném odkazu prosím udělejte jako pop-up okno do středu stránky. 

Celkově to kvůli tmavé modré a tmavému pozadí působí tak trochu těžce a tmavě. Prosím o středový blok ve světle šedé s černým textem. A asi i tlačítko konvertovat by bylo vyraznější ve světle šedé, protože to už je téměř na černém pozadí a zapadá. 

![ocr-hp-svetlejsi](https://user-images.githubusercontent.com/15922183/66380862-7d7b5600-e9b8-11e9-8fff-dc5c03b457c2.png)
