### ISSUE TITLE
OCR nefunguje

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU-OCR#4]
INDIHU ocr mi nefunguje (https://ocr.indihu.cz/). 

Nahraju obrázek (jpg), vyberu formát a jazyk a dám konvertovat a nic, jen se točí a točí (když chci výstupní formát PDF):
![1](https://user-images.githubusercontent.com/21309201/212092727-6a4bbe87-a1fc-4bf1-9724-a811dfd323d3.jpg)

Když chci jako výstupní formát txt, tak mi vyhodí tohle:
![2](https://user-images.githubusercontent.com/21309201/212092885-4030b17b-82aa-4a6f-aede-9af93074a9e7.jpg)

Stejnou věc dělá chrome i firefox, z jazyků jsem zkoušela češtinu a angličtinu.

**Comment by rudky4** [comment]
Opraveno, aktualizace PHP.
